version: "3"
services:
  api:
    image: abs/ts-api
    ports:
      - "5000:3050"
    links:
      - "link-db"
  link-db:
    image: tutum/mongodb
    ports:
      - "27017:27017"
      - "28017:28017"
    environmnt:
      - AUTH=no
